services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434" # Expose Ollama API
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped

  flask-app:
    build: .
    ports:
      - "5000:5000" # Expose Flask app
    depends_on:
        - ollama
    environment:
      - OLLAMA_API_URL=http://ollama:11434
      - OLLAMA_MODEL=${OLLAMA_MODEL:-gemma3:1b}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - PRODUCTION_ENVIROMENT=True
    volumes:
      - ./static:/static
      - ./templates:/templates
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  ollama_data: