services:
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
    restart: unless-stopped

  flask-app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - ollama
    environment:
      - OLLAMA_API_URL=http://ollama:11434
      - OLLAMA_MODEL=${OLLAMA_MODEL:-gemma3:1b}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
    volumes:
      - ./static:/app/static
      - ./templates:/app/templates
    restart: unless-stopped

volumes:
  ollama_data: